CREATE TABLE hr.trx (
  outlet_key NUMBER,
  trading_date DATE,
  processing_date DATE,
  transaction_datetime DATE,
  transaction_date DATE,
  card_number_length NUMBER,
  card_number_left NUMBER,
  cardt_number_right NUMBER,
  card_expiry_date CHAR(5 BYTE),
  card_issuer_number CHAR(2 BYTE),
  card_start_date CHAR(5 BYTE),
  transaction_type_key NUMBER,
  transaction_source_key NUMBER,
  settlement_amount NUMBER,
  settlement_currency_key CHAR(3 BYTE),
  transaction_amount NUMBER,
  transaction_currency_key CHAR(3 BYTE),
  acquired_processed_key NUMBER,
  card_product_key NUMBER,
  card_product_type_key NUMBER,
  card_scheme_key NUMBER,
  sequence_no NUMBER,
  auth_code VARCHAR2(16 BYTE),
  auth_method_key NUMBER,
  receipt_number NUMBER,
  cash_amount NUMBER,
  originators_transaction_ref VARCHAR2(59 BYTE),
  ticket_number NUMBER
);